name: domain
description: A starting point for Dart libraries or applications.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0
