name: presentation
description: A starting point for Dart libraries or applications.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  get_it: ^7.6.4
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  domain:
    path: ../domain
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
