name: presentation
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  bloc: ^8.1.2
  domain:
    path: ../domain
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  meta: ^1.9.1
  service_locator:
    path: ../../dependencies/service_locator
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
