name: clean_architecture_template_application
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  app_module:
    path: application/presentation/app_module
  authentication_domain:
    path: application/domain/authentication_domain   
  authentication_module:
    path: application/presentation/authentication_module
  authentication_repository:
    path: application/data/authentication_repository
  flutter:
    sdk: flutter
  home_module:
    path: application/presentation/home_module
  rest_data_source_adapter:
    path: dependencies/data_source_adapters/rest_data_source_adapter
  secure_local_storage_data_source_adapter:
    path: dependencies/data_source_adapters/secure_local_storage_data_source_adapter
  service_locator:
    path: dependencies/service_locator
  user_domain:
    path: application/domain/user_domain
  user_repository:
    path: application/data/user_repository

dev_dependencies:
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true