name: clean_architecture_template_application
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  app:
    path: features/app
  authentication:
    path: features/authentication
  authentication_repository:
    path: repositories/authentication_repository
  flutter:
    sdk: flutter
  home:
    path: features/home
  rest_data_source_adapter:
    path: dependencies/data_source_adapters/rest_data_source_adapter
  secure_local_storage_data_source_adapter:
    path: dependencies/data_source_adapters/secure_local_storage_data_source_adapter
  secure_preferences_repository:
    path: repositories/secure_preferences_repository
  service_locator:
    path: dependencies/service_locator
  usecases:
    path: usecases
  user_repository:
    path: repositories/user_repository

dev_dependencies:
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true