name: secure_local_storage_data_source_adapter
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  very_good_analysis: ^5.1.0
