name: authentication
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  authentication_repository:
    path: ../../repositories/authentication_repository
  bloc: ^8.1.2
  core:
    path: ../../dependencies/core
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  meta: ^1.9.1
  purple_ui:
    path: ../../dependencies/purple_ui
  rest_data_source_adapter:
    path: ../../dependencies/data_source_adapters/rest_data_source_adapter
  secure_local_storage_data_source_adapter:
    path: ../../dependencies/data_source_adapters/secure_local_storage_data_source_adapter
  service_locator:
    path: ../../dependencies/service_locator
  usecases:
    path: ../../usecases

dev_dependencies:
  very_good_analysis: ^5.1.0