include: package:very_good_analysis/analysis_options.yaml
analyzer:
  language:
    strict-casts: false
    strict-inference: false

linter:
  rules:
    public_member_api_docs: false
    avoid_dynamic_calls: false
    one_member_abstracts: false
    lines_longer_than_80_chars: false
    avoid_positional_boolean_parameters: false
    implementation_imports: false
