name: core
description: A starting point for Dart libraries or applications.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  data: 
    path: ../data
  domain:
    path: ../domain
  get_it: ^7.6.4
  presentation:
    path: ../presentation

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.21.0
  very_good_analysis: ^5.1.0
