name: home_module
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  app_module:
    path: ../app_module
  authentication_module:
    path: ../authentication_module
  bloc: ^8.1.2
  core:
    path: ../../../dependencies/core
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  service_locator:
    path: ../../../dependencies/service_locator
  user_domain:
    path: ../../domain/user_domain

dev_dependencies:
  very_good_analysis: ^5.1.0