name: app_module
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  authentication_module:
    path: ../authentication_module
  bloc: ^8.1.2
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  home_module:
    path: ../home_module
  purple_ui:
    path: ../../../dependencies/purple_ui
  service_locator:
    path: ../../../dependencies/service_locator

dev_dependencies:
  very_good_analysis: ^5.1.0