name: authentication_module
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  authentication_domain:
    path: ../../domain/authentication_domain
  bloc: ^8.1.2
  core_domain:
    path: ../../domain/core_domain
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  meta: ^1.9.1
  purple_ui:
    path: ../../../dependencies/purple_ui
  service_locator:
    path: ../../../dependencies/service_locator

dev_dependencies:
  very_good_analysis: ^5.1.0