name: secure_preferences_repository
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  core:
    path: ../../dependencies/core
  equatable: ^2.0.5
  flutter_secure_storage: ^9.0.0
  secure_local_storage_data_source_adapter:
    path: ../../dependencies/data_source_adapters/secure_local_storage_data_source_adapter

dev_dependencies:
  very_good_analysis: ^5.1.0