name: usecases
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  authentication_repository:
    path: ../repositories/authentication_repository
  core:
    path: ../dependencies/core
  equatable: ^2.0.5
  user_repository:
    path: ../repositories/user_repository

dev_dependencies:
  very_good_analysis: ^5.1.0
