name: authentication_domain
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  core:
    path: ../core
  equatable: ^2.0.5

dev_dependencies:
  very_good_analysis: ^5.1.0
