name: authentication_repository
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  core:
    path: ../../dependencies/core
  equatable: ^2.0.5
  rest_data_source_adapter:
    path: ../../dependencies/data_source_adapters/rest_data_source_adapter
  secure_preferences_repository:
    path: ../secure_preferences_repository
  usecases:
    path: ../../usecases

dev_dependencies:
  very_good_analysis: ^5.1.0
